### PR TITLE
Auto Install latest Golang

### PR DESCRIPTION
**Pull request by KathanP19**
Auto Install Golang and set Proper Path.

### CODE REVIEW

**Comment by vlakhani28** [comment]
Are you sure this works?

**Comment by KathanP19** [comment]
I have tested it you can try from your side

**Comment by vlakhani28** [comment]
Cool I will try it once and then pull the request

**Comment by vlakhani28** [comment]
image

Tested it brother, it does not work :)

**Comment by KathanP19** [comment]
hmm... what different i did let me check

**Comment by vlakhani28** [comment]
Sure :)

**Comment by KathanP19** [comment]
Actually it got install in /root/ directory so you have to do `source /root/.bashrc` to make it work

**Comment by KathanP19** [comment]
Also can you change the terminal to default if possible

**Comment by vlakhani28** [comment]
> Actually it got install in /root/ directory so you have to do `source /root/.bashrc` to make it work

I had tried this before, it told me source command not found
image

**Comment by KathanP19** [comment]
what i did in my installation script is 
```
#Install Golang.
echo -e "Installing Go-Lang";
wget -q -O - https://git.io/vQhTU | bash
echo "source ~/.bashrc" >> ~/.bash_profile
source ~/.bash_profile
echo -e " ";
```
and run script as `. ./install.sh`

**Comment by KathanP19** [comment]
You can edit your bbht script and add this

**Comment by vlakhani28** [comment]
> Also can you change the terminal to default if possible

The Linux System we use to deploy our VPS is Xfce which is light weight Linux system so the default terminal will remain the same.

Alternatively, you can install Tilda as an alternative terminal using the command : apt-get install tilda

**Comment by vlakhani28** [comment]
> what i did in my installation script is
> 
> ```
> #Install Golang.
> echo -e "Installing Go-Lang";
> wget -q -O - https://git.io/vQhTU | bash
> echo "source ~/.bashrc" >> ~/.bash_profile
> source ~/.bash_profile
> echo -e " ";
> ```
> 
> and run script as `. ./install.sh`

I tried this too, does not help out :)

**Comment by KathanP19** [comment]
Hmm... bad luck, I think I have to stay with google collab only, nice try though

**Comment by vlakhani28** [comment]
Well depends on you, in google collab you need to install tools every time you login, here it is pre installed.

**Comment by KathanP19** [comment]
Thats not 100% true 😃  https://github.com/hackingguy/Bug-Hunting-Colab

**Comment by vlakhani28** [comment]
I mean it stays for 12 hours (or so) right and then you will need to re run to create the ssh tunnel which will create a new set of credentials for you and since it does not come with pre installed tools you need to re install everything correct me if am wrong

**Comment by KathanP19** [comment]
Yup, that's true though

**Pull request closed without merging**
